### PR TITLE
Pages to get input data from users

### PR DESCRIPTION
**Pull request by Inyong-Hwang**
I made pages to get input data such as subjects, exam date, difficulty, study preference from users.
I'm waiting for your review hope those pages would contribute to our web improvement.

### CODE REVIEW

**Comment by Inyong-Hwang** [comment]
I think some errors happens same with previous PRs in CI. Please Help me!

**Review by JunheePark0224 — APPROVED** [review]
First of all, I apologize for the errors in the testing files. I believe there are some issues that need to be resolved, and I will address them as soon as possible. However, based on the description provided in GitHub Actions, these errors do not seem related to the changes in your code. Therefore, I believe we can safely merge this pull request, and I will fix the testing issues afterward.

Secondly, I really appreciate the great design and effort put into this implementation. However, I have some suggestions for improving the content in the steps:

Step 1: Subject Information
The following items should be included:

Subject
Exam range
Exam date
Study time
Difficulty (indicate the difficulty of the workbook or materials the student wants to study)
Additionally, subjects can be added dynamically by using a "plus" button.

Step 2: Study Style
This step should focus on individual study styles for each student. Suggested items:

Study style (e.g., short, focused sessions or longer, immersive sessions)
Break preferences (e.g., short breaks, long breaks)
Step 3: Additional Study Preferences
This step could enhance the customization of study plans. Suggested items:

Daily goal setting (e.g., how many hours to study each day)
Lifestyle patterns (e.g., daily schedules like school/academy hours to calculate available study time, weekend preferences for intensive studying)
Step 4: Mock Test Integration (Optional)
Consider adding this step for our Pro version as an optional feature. Users could skip this step by simply clicking the confirmation button.

I hope these suggestions help refine the process and improve the user experience. Let me know if you have any questions or need clarification! Thanks for your consistent contributing!

**Comment by JunheePark0224** [comment]
I would first merge it and then let's develop it together step by step:)

**Comment by Inyong-Hwang** [comment]
I appreciate your delicate review. Also, based on your review, I understood how to put input data for student in detail. Based on this, I will write the code and PR it as soon as possible. Have a nice day :)

**Pull request merged**
