### PR TITLE
Initialpage

### PR DESCRIPTION
**Pull request by Inyong-Hwang**
Can you review?

### CODE REVIEW

**Comment by kwonjaeuk** [comment]
Good We can modify a bit to make it perfect. Well done!

**Comment by JunheePark0224** [comment]
Thanks for making our website's initial page. I think it is really important work and it looks great. More improvement, more challenge, let's make our website together!

**Review by kwonjaeuk — COMMENTED** [review]
Good! We can develop more on this.

**Comment by kwonjaeuk** [comment]
> Good! We can develop more on this.

**Review by JunheePark0224 — APPROVED** [review]
I think there is not any error in this code..? Well done!

**Pull request merged**
