### PR TITLE
loginchange

### PR DESCRIPTION
**Pull request by woojeonghyuk**

### CODE REVIEW

**Review by kwonjaeuk — COMMENTED** [review]
Great job! I love the design of your page. Thanks for your work.

**Review by kwonjaeuk — APPROVED** [review]
Great job! I love the design of your page. Thanks for your work.

**Comment by JunheePark0224** [comment]
image
Thank you how about making the logo slightly bigger?? I'd really appreciate if you consider it! :)

**Comment by Inyong-Hwang** [comment]
Well done! I think it will attracts many students!!

**Pull request merged**
